language: java
jdk:
  - oraclejdk8
  - oraclejdk9
dist: trusty

branches:
  only:
    - assignment-part7

before_install:
  - java -version

install:
  - ./gradlew clean jar

stages:
  - tests
  - tests-report
  - deploy

jobs:
  include:
    - stage: tests
      env:
        - COVERAGE=0.5
      script:
        - ./gradlew -p ./monolithic/ui check
    - stage: tests
      env:
        - COVERAGE=0.5
      script:
        - ./gradlew -p ./monolithic/service/cart check
    - stage: tests
      env:
        - COVERAGE=0.5
      script:
        - ./gradlew -p ./monolithic/service/user check
    - stage: tests
      env:
        - COVERAGE=0.24
      script:
        - ./gradlew -p ./monolithic/repository/order check
    - stage: tests
      env:
        - COVERAGE=0.5
      script:
        - ./gradlew -p ./monolithic/repository/cart check
    - stage: tests
      env:
        - COVERAGE=0.5
      script:
        - ./gradlew -p ./monolithic/repository/product check
    - stage: tests
      env:
        - COVERAGE=0.24
      script:
        - ./gradlew -p ./monolithic/repository/user check

    - stage: tests-report
      name: "Test-Report"
      script:
        - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'

    - stage: deploy #Temporary deploy
      name: "Deployment"
      script:
        - echo 'WIP'
      deploy:
        skip_cleanup: true

notifications:
  email: false
