language: java
jdk: oraclejdk8
dist: trusty

branches:
  only:
    - assignment-part5

before_install:
  - java -version

install:
  - ./gradlew clean jar

stages:
  - tests
  - tests-coverage
  - test-report
  - deploy

jobs:
    - stage: tests
      name: "Tests"
      script:
        - ./gradlew test
        - ./gradlew jacocoTestReport

    - stage: tests-coverage
      name: "Test-Coverage"
      script:
        - COVERAGE=0.7 ./gradlew test jacocoTestCoverageVerification

    - stage: tests-coverage
      name: "Test-Coverage"
      script:
        - COVERAGE=0.6 ./gradlew test jacocoTestCoverageVerification

    - stage: tests-coverage
      name: "Test-Coverage"
      script:
        - COVERAGE=0.5 ./gradlew test jacocoTestCoverageVerification

    - stage: tests-coverage
      name: "Test-Coverage"
      script:
        - COVERAGE=0.4 ./gradlew test jacocoTestCoverageVerification

    - stage: tests-coverage
      name: "Test-Coverage"
      script:
        - COVERAGE=0.3 ./gradlew test jacocoTestCoverageVerification

    - stage: tests-coverage
      name: "Test-Coverage"
      script:
        - COVERAGE=0.2 ./gradlew test jacocoTestCoverageVerification

    - stage: tests-coverage
      name: "Test-Coverage"
      script:
        - COVERAGE=0.1 ./gradlew test jacocoTestCoverageVerification

    - stage: test-report
      name: "Test-Report"
      script:
        - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'

    - stage: deploy #Temporary deploy
      name: "Deployment"
      script:
        - echo 'WIP'
      deploy:
        skip_cleanup: true

notifications:
  email: false
