language: java
dist: trusty
services:
  - docker

branches:
  only:
    - assignment-part8

install:
  - ./gradlew clean jar

script:
  - travis encrypt DOCKER_PASSWORD-password --add env.global --com
  - docker login -u="$DOCKER_USERNAME" -p"$DOCKER_PASSWORD"
  - bash -c "echo \"${DOCKER_PASSWORD}\" | docker login --username \"$DOCKER_LOGIN\" --password-stdin"

stages:
  - test #actually docker login
  - tests
  - tests-report
  - deploy

#Mssd15807do

jobs:
  include:
    # JDK8
    - stage: tests
      jdk:
        - oraclejdk8
      env:
        - COVERAGE=0.5
      script:
        - ./gradlew -p ./monolithic/ui check
    - stage: tests
      jdk: oraclejdk8
      env:
        - COVERAGE=0.5
      script:
        - ./gradlew -p ./monolithic/service/cart check
    - stage: tests
      jdk: oraclejdk8
      env:
        - COVERAGE=0.5
      script:
        - ./gradlew -p ./monolithic/service/user check
    - stage: tests
      jdk: oraclejdk8
      env:
        - COVERAGE=0.24
      script:
        - ./gradlew -p ./monolithic/repository/order check
    - stage: tests
      jdk: oraclejdk8
      env:
        - COVERAGE=0.5
      script:
        - ./gradlew -p ./monolithic/repository/cart check
    - stage: tests
      jdk: oraclejdk8
      env:
        - COVERAGE=0.5
      script:
        - ./gradlew -p ./monolithic/repository/product check
    - stage: tests
      jdk: oraclejdk8
      env:
        - COVERAGE=0.24
      script:
        - ./gradlew -p ./monolithic/repository/user check

    # JDK9
    - stage: tests
      jdk:
        - oraclejdk9
      env:
        - COVERAGE=0.5
      script:
        - ./gradlew -p ./monolithic/ui check
    - stage: tests
      jdk: oraclejdk9
      env:
        - COVERAGE=0.5
      script:
        - ./gradlew -p ./monolithic/service/cart check
    - stage: tests
      jdk: oraclejdk9
      env:
        - COVERAGE=0.5
      script:
        - ./gradlew -p ./monolithic/service/user check
    - stage: tests
      jdk: oraclejdk9
      env:
        - COVERAGE=0.24
      script:
        - ./gradlew -p ./monolithic/repository/order check
    - stage: tests
      jdk: oraclejdk9
      env:
        - COVERAGE=0.5
      script:
        - ./gradlew -p ./monolithic/repository/cart check
    - stage: tests
      jdk: oraclejdk9
      env:
        - COVERAGE=0.5
      script:
        - ./gradlew -p ./monolithic/repository/product check
    - stage: tests
      jdk: oraclejdk9
      env:
        - COVERAGE=0.24
      script:
        - ./gradlew -p ./monolithic/repository/user check

    - stage: tests-report
      name: "Test-Report"
      script:
        - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'

    - stage: deploy #Temporary deploy
      name: "Deployment"
      script:
        - echo 'WIP'
      deploy:
        skip_cleanup: true

notifications:
  email: false
