language: java
jdk: oraclejdk8
dist: trusty

before_install:
  - java -version

stages:
  - build
  - tests
  - tests-coverage #executes only if "tests" runs

jobs:
  include:
    - stage: build
      name: "Build"
      script:
        - ./gradlew clean jar

    - stage: tests
      name: "Test"
      script:
        - ./gradlew test
        
    - stage: tests-coverage
      name: "Test-Coverage"
      script:
        - ./gradlew jacocoTestReport
        - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'

notifications:
  email: false
