language: java
jdk: oraclejdk8
dist: trusty

before_install:
  - java -version

install:
  - ./gradlew clean jar

stages:
  - tests

jobs:
  include:
    - stage: tests
      script: echo 'testing coming soon'

notifications:
  email: false
