language: java
os: linux
dist: trusty
sudo: required
services:
  - docker

branches:
  only:
    - assignment-part8

addons:
  apt:
    packages:
      - openssl

env:
  jobs:
    - JDK_VERSION=oraclejdk8
    - JDK_VERSION=oraclejdk9
  global:
    - DOCKER_USERNAME=martbarc
    - DOCKER_PASSWORD=Mssd15807do

install:
  - ./gradlew clean jar

script:
  - openssl version -a
  - gem install travis #--debug
  - travis endpoint --com --adapter net-http --set-default
  #- curl -H "Authorization: token **TOKEN**" https://api.travis-ci.org/v3/repo/travis-ci%2ftravis-build/key_pair/generated
  #- curl -H "Authorization: token **TOKEN**" https://api.travis-ci.com/v3/repo/OWNER%2fREPO/key_pair/generated
  - travis login --github-token ${PERSONAL_FULL_TOKEN} --com --adapter net-http
  - travis report --com --adapter net-http
  #- travis whoami --com --debug
  - travis whoami --com --adapter net-http
  #- travis env set DOCKER_USERNAME myusername
  #- travis env set DOCKER_PASSWORD secretsecret
  - travis pubkey --com --adapter net-http MartBarc/WEB1066-the-app
  - travis encrypt DOCKER_USERNAME=martbarc -r MartBarc/WEB1066-the-app --com --adapter net-http --debug
  - travis encrypt DOCKER_PASSWORD=Mssd15807do -r MartBarc/WEB1066-the-app --add env.global --com --adapter net-http --debug
  - echo "$DOCKER_USERNAME"
  - docker login -u $DOCKER_TEMP_USER -p DOCKER_TEMP_PASS
  # - echo "$DOCKER_PASSWORD" | docker login --"$DOCKER_USERNAME" foo --password-stdin 
  - bash -c "echo \"${DOCKER_PASSWORD}\" | docker login --username\"$DOCKER_LOGIN\" --password-stdin"
  #docker push martbarc/web1066-the-app:tagname

stages:
  - test #actually docker stage
  - tests-check
  - tests-report
  - deploy

jobs:
  include:
    # JDK8
    - stage: tests-check
      jdk:
        - oraclejdk8
      env:
        - COVERAGE=0.5
      script:
        - ./gradlew -p ./monolithic/ui check
    - stage: tests-check
      jdk: oraclejdk8
      env:
        - COVERAGE=0.5
      script:
        - ./gradlew -p ./monolithic/service/cart check
    - stage: tests-check
      jdk: oraclejdk8
      env:
        - COVERAGE=0.5
      script:
        - ./gradlew -p ./monolithic/service/user check
    - stage: tests-check
      jdk: oraclejdk8
      env:
        - COVERAGE=0.24
      script:
        - ./gradlew -p ./monolithic/repository/order check
    - stage: tests-check
      jdk: oraclejdk8
      env:
        - COVERAGE=0.5
      script:
        - ./gradlew -p ./monolithic/repository/cart check
    - stage: tests-check
      jdk: oraclejdk8
      env:
        - COVERAGE=0.5
      script:
        - ./gradlew -p ./monolithic/repository/product check
    - stage: tests-check
      jdk: oraclejdk8
      env:
        - COVERAGE=0.24
      script:
        - ./gradlew -p ./monolithic/repository/user check

    # JDK9
    - stage: tests-check
      jdk:
        - oraclejdk9
      env:
        - COVERAGE=0.5
      script:
        - ./gradlew -p ./monolithic/ui check
    - stage: tests-check
      jdk: oraclejdk9
      env:
        - COVERAGE=0.5
      script:
        - ./gradlew -p ./monolithic/service/cart check
    - stage: tests-check
      jdk: oraclejdk9
      env:
        - COVERAGE=0.5
      script:
        - ./gradlew -p ./monolithic/service/user check
    - stage: tests-check
      jdk: oraclejdk9
      env:
        - COVERAGE=0.24
      script:
        - ./gradlew -p ./monolithic/repository/order check
    - stage: tests-check
      jdk: oraclejdk9
      env:
        - COVERAGE=0.5
      script:
        - ./gradlew -p ./monolithic/repository/cart check
    - stage: tests-check
      jdk: oraclejdk9
      env:
        - COVERAGE=0.5
      script:
        - ./gradlew -p ./monolithic/repository/product check
    - stage: tests-check
      jdk: oraclejdk9
      env:
        - COVERAGE=0.24
      script:
        - ./gradlew -p ./monolithic/repository/user check

    - stage: tests-report
      name: "Test-Report"
      script:
        - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'

    - stage: deploy #Temporary deploy
      name: "Deployment"
      script:
        - echo 'WIP'
      deploy:
        skip_cleanup: true

notifications:
  email: false
