language: java
jdk: oraclejdk8
dist: trusty

env:
  - COVERAGE=0.5 #expected
  - COVERAGE=0.4
  - COVERAGE=0.3
  - COVERAGE=0.2
  - COVERAGE=0.1

branches:
  only:
    - assignment-part5

before_install:
  - java -version

install:
  - ./gradlew clean jar

script:
  - ./gradlew test
  - ./gradlew jacocoTestReport
  - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'
  - ./gradlew test jacocoTestCoverageVerification

deploy:
  script:
    - echo 'WIP'
  cleanup: true

notifications:
  email: false
