language: java
jdk: oraclejdk8
dist: trusty

env:
  - COVERAGE=0.6
  - COVERAGE=0.5
  - COVERAGE=0.4
  - COVERAGE=0.3
  - COVERAGE=0.2
  - COVERAGE=0.1

branches:
  only:
    - assignment-part5

before_install:
  - java -version

install:
  - ./gradlew clean jar

stages:
  - tests
  - test-report
  - tests-coverage
  - deploy

jobs:
  include:
    - stage: tests
      name: "Tests"
      script:
        - ./gradlew test

    - stage: test-report
      name: "Test-Report"
      script:
        - ./gradlew jacocoTestReport
        - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'

    - stage: tests-coverage
      name: "Test-Coverage"
      script:
        - ./gradlew test jacocoTestCoverageVerification

    - stage: deploy #Temporary deploy
      name: "Deployment"
      script:
        - echo 'WIP'
      deploy:
        skip_cleanup: true

notifications:
  email: false
