language: java
jdk: oraclejdk8
dist: trusty

branches:
  only:
    - assignment-part3

before_install:
  - java -version

install:
  - ./gradlew clean jar

stages:
  - tests
  - tests-coverage
  - deploy

jobs:
    - stage: tests
      name: "Test"
      script:
        - ./gradlew test

    - stage: tests-coverage
      name: "Test-Coverage"
      script:
        - ./gradlew jacocoTestReport
        - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'
        - ./gradlew test jaccoTestCoverageVerification

    - stage: deploy #Temporary deploy
      name: "Deployment"
      script:
        - echo 'WIP'
      deploy:
        skip_cleanup: true

notifications:
  email: false
