language: java
dist: trusty
sudo: required
services:
  - docker

branches:
  only:
    - assignment-part8

env:
   - JDK_VERSION=oraclejdk8
   - JDK_VERSION=oraclejdk9

install:
  - ./gradlew clean jar

script:
  - gem install travis --pre
  - travis login --org
  #- travis env set DOCKER_USERNAME myusername
  #- travis env set DOCKER_PASSWORD secretsecret
  - travis encrypt DOCKER_USERNAME="martbarc" --add env.global --adapter net-http
  - travis encrypt DOCKER_PASSWORD="Mssd15807do" --add env.global --adapter net-http
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - bash -c "echo \"${DOCKER_PASSWORD}\" | docker login --username\"$DOCKER_LOGIN\" --password-stdin"
  #docker push martbarc/web1066-the-app:tagname

stages:
  - test #actually docker stage
  - tests-check
  - tests-report
  - deploy

jobs:
  include:
    # JDK8
    - stage: tests-check
      jdk:
        - oraclejdk8
      env:
        - COVERAGE=0.5
      script:
        - ./gradlew -p ./monolithic/ui check
    - stage: tests-check
      jdk: oraclejdk8
      env:
        - COVERAGE=0.5
      script:
        - ./gradlew -p ./monolithic/service/cart check
    - stage: tests-check
      jdk: oraclejdk8
      env:
        - COVERAGE=0.5
      script:
        - ./gradlew -p ./monolithic/service/user check
    - stage: tests-check
      jdk: oraclejdk8
      env:
        - COVERAGE=0.24
      script:
        - ./gradlew -p ./monolithic/repository/order check
    - stage: tests-check
      jdk: oraclejdk8
      env:
        - COVERAGE=0.5
      script:
        - ./gradlew -p ./monolithic/repository/cart check
    - stage: tests-check
      jdk: oraclejdk8
      env:
        - COVERAGE=0.5
      script:
        - ./gradlew -p ./monolithic/repository/product check
    - stage: tests-check
      jdk: oraclejdk8
      env:
        - COVERAGE=0.24
      script:
        - ./gradlew -p ./monolithic/repository/user check

    # JDK9
    - stage: tests-check
      jdk:
        - oraclejdk9
      env:
        - COVERAGE=0.5
      script:
        - ./gradlew -p ./monolithic/ui check
    - stage: tests-check
      jdk: oraclejdk9
      env:
        - COVERAGE=0.5
      script:
        - ./gradlew -p ./monolithic/service/cart check
    - stage: tests-check
      jdk: oraclejdk9
      env:
        - COVERAGE=0.5
      script:
        - ./gradlew -p ./monolithic/service/user check
    - stage: tests-check
      jdk: oraclejdk9
      env:
        - COVERAGE=0.24
      script:
        - ./gradlew -p ./monolithic/repository/order check
    - stage: tests-check
      jdk: oraclejdk9
      env:
        - COVERAGE=0.5
      script:
        - ./gradlew -p ./monolithic/repository/cart check
    - stage: tests-check
      jdk: oraclejdk9
      env:
        - COVERAGE=0.5
      script:
        - ./gradlew -p ./monolithic/repository/product check
    - stage: tests-check
      jdk: oraclejdk9
      env:
        - COVERAGE=0.24
      script:
        - ./gradlew -p ./monolithic/repository/user check

    - stage: tests-report
      name: "Test-Report"
      script:
        - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'

    - stage: deploy #Temporary deploy
      name: "Deployment"
      script:
        - echo 'WIP'
      deploy:
        skip_cleanup: true

notifications:
  email: false
